pipeline:

    build:
      image: kowalatech/hugo-dev:1.0.4
      commands:
        - make docker-build
      when:
        branch: [develop, master]

    staging:
      image: plugins/s3
      acl: public-read
      region: "eu-west-1"
      bucket: "www.staging.endian.io"
      source: public/**/*
      strip_prefix: public/
      target: /
      encryption: AES256
      when:
        branch: [develop]
        event: [push, tag]

    production:
      image: plugins/s3
      acl: public-read
      region: "eu-west-2"
      bucket: "endian.io"
      source: public/**/*
      strip_prefix: public/
      target: /
      encryption: AES256
      when:
        branch: master
        event: [push, tag]
