pipeline:

    build-staging:
      image: kowalatech/hugo-dev:1.0.5
      environment:
        - HUGO_ENV="staging"
        - HUGO_BASEURL="http://www.staging.endian.io"
      commands:
        - make docker-build
      when:
        branch: [develop]
        event: [push, tag]

    build-production:
      image: kowalatech/hugo-dev:1.0.5
      environment:
        - HUGO_ENV="production"
        - HUGO_BASEURL="https://endian.io"
      commands:
        - make docker-build
      when:
        branch: [master]
        event: [push, tag]

    staging:
      image: plugins/s3
      acl: public-read
      region: "eu-west-1"
      bucket: "www.staging.endian.io"
      source: public/**/*
      strip_prefix: public/
      target: /
      encryption: AES256
      when:
        branch: [develop, feature/article-layout]
        event: [push, tag]

    production:
      image: plugins/s3
      acl: public-read
      region: "eu-west-2"
      bucket: "endian.io"
      source: public/**/*
      strip_prefix: public/
      target: /
      encryption: AES256
      when:
        branch: master
        event: [push, tag]
