---
kind: pipeline
name: endian.io

platform:
  os: linux
  arch: amd64

steps:
- name: build-staging
  image: endian/hugo:1.0.1
  commands:
  - make docker-build
  environment:
    HUGO_BASEURL: http://www.staging.endian.io
    HUGO_ENV: staging
  when:
    branch:
    - develop
    - feature/colour-experiment
    event:
    - push
    - tag

- name: build-production
  image: endian/hugo:1.0.1
  commands:
  - make docker-build
  environment:
    HUGO_BASEURL: https://endian.io
    HUGO_ENV: production
  when:
    branch:
    - master
    event:
    - push
    - tag

- name: staging
  image: plugins/s3
  when:
    branch:
    - develop
    - feature/colour-experiment
    event:
    - push
    - tag

- name: production
  image: plugins/s3
  when:
    event:
    - push
    - tag

...
