# Hugo params for global setup
languageCode    = "en-us"
title           = "Endian Group"
theme           = "sherpa"
enableRobotsTXT = true

# Site-wide content params
[params]
	description = "Holistic technical solutions from first principles to world domination."
	author			= "Endian Group"

	##############################################################
    # This is the ASCII art in the output source code. It looks
    # garbled here because it has no line breaks.
	##############################################################

  headerComment = "\n######## ##    ## ########  ####    ###    ##    ##     ####  #######  \n##       ###   ## ##     ##  ##    ## ##   ###   ##      ##  ##     ## \n##       ####  ## ##     ##  ##   ##   ##  ####  ##      ##  ##     ## \n######   ## ## ## ##     ##  ##  ##     ## ## ## ##      ##  ##     ## \n##       ##  #### ##     ##  ##  ######### ##  ####      ##  ##     ## \n##       ##   ### ##     ##  ##  ##     ## ##   ### ###  ##  ##     ## \n######## ##    ## ########  #### ##     ## ##    ## ### ####  #######  \nMade with Hugo + Foundation 6.\n"

  [[menu.main]]
  name = "Home"
  url  = "/"
  pre = "mountains"
  weight = 1

  [[menu.main]]
  name = "Theory"
  url  = "/theory"
  pre = "book"
  weight = 2

  [[menu.main]]
  name = "Articles"
  url  = "/articles"
  pre = "comment-quotes"
  weight = 3

  [[menu.secondary]]
  name = "GitHub"
  url  = "https://github.com/endiangroup"
  pre = "social-github"
  weight = 1

  [[menu.secondary]]
  name = "LinkedIn"
  url  = "https://www.linkedin.com/company/endian-group/about"
  pre = "social-linkedin"
  weight = 2
